In [2]:
#Array（数组）

In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [5]:
type(a)

numpy.ndarray

In [6]:
a.shape

(3,)

In [7]:
a.reshape(1,3)

array([[1, 2, 3]])

In [8]:
a.reshape(1,-1)

array([[1, 2, 3]])

In [18]:
a=a.reshape(3,1)

In [19]:
a.shape

(3, 1)

In [20]:
a

array([[1],
       [2],
       [3]])

In [21]:
a[1,0]=5

In [22]:
a

array([[1],
       [5],
       [3]])

In [23]:
a=np.zeros((3,3))

In [24]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
a=np.full((2,3),6)

In [26]:
a

array([[6, 6, 6],
       [6, 6, 6]])

In [27]:
a=np.eye(3)

In [28]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
a=np.random.random((3,4))

In [30]:
a

array([[0.07500591, 0.45532728, 0.37548677, 0.61603801],
       [0.40074222, 0.74196251, 0.80208821, 0.98418311],
       [0.65572112, 0.08316262, 0.23150169, 0.28795226]])

In [32]:
a=np.array([[1,2,3,4],
           [4,5,6,7],
           [8,9,10,11]])

In [35]:
a[-2:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [36]:
b=a[-3:-1,1:3]

In [37]:
b.shape

(2, 2)

In [38]:
b

array([[2, 3],
       [5, 6]])

In [39]:
a[np.arange(3),1]+=10

In [40]:
a

array([[ 1, 12,  3,  4],
       [ 4, 15,  6,  7],
       [ 8, 19, 10, 11]])

In [41]:
np.arange(3)

array([0, 1, 2])

In [42]:
np.arange(3,7)

array([3, 4, 5, 6])

In [43]:
a[np.arange(3),[1,1,1]]+=10

In [44]:
a

array([[ 1, 22,  3,  4],
       [ 4, 25,  6,  7],
       [ 8, 29, 10, 11]])

In [45]:
a[[0,1,2],[1,1,1]]+=10

In [46]:
a

array([[ 1, 32,  3,  4],
       [ 4, 35,  6,  7],
       [ 8, 39, 10, 11]])

In [47]:
result_index=a>10

In [48]:
result_index

array([[False,  True, False, False],
       [False,  True, False, False],
       [False,  True, False,  True]])

In [49]:
a[result_index]

array([32, 35, 39, 11])

In [50]:
a[a>10]

array([32, 35, 39, 11])

In [51]:
a[a>20]

array([32, 35, 39])

In [52]:
a=np.array([1,2,2])

In [54]:
a.dtype

dtype('int32')

In [56]:
a=np.array([2.2,3.3])
a.dtype

dtype('float64')

In [58]:
a=np.array([1.1,2.6],dtype=np.int32)

In [59]:
a

array([1, 2])

In [60]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a+b

array([5, 7, 9])

In [61]:
np.add(a,b)#与上面相似

array([5, 7, 9])

In [62]:
a-b

array([-3, -3, -3])

In [63]:
np.subtract(a,b)#与上面相似

array([-3, -3, -3])

In [64]:
a*b

array([ 4, 10, 18])

In [65]:
np.multiply(a,b)

array([ 4, 10, 18])

In [66]:
a/b

array([0.25, 0.4 , 0.5 ])

In [67]:
np.divide(a,b)

array([0.25, 0.4 , 0.5 ])

In [68]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [69]:
a

array([1, 2, 3])

In [72]:
b=np.array([[1],
          [3],
          [9]])
a.dot(b)#矩阵乘法 列和行要相等

array([34])

In [73]:
np.dot(a,b)

array([34])

In [77]:
a=np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])
np.sum(a)

45

In [78]:
np.sum(a,axis=0)#每列数字相加

array([12, 15, 18])

In [79]:
np.sum(a,axis=1)#每行数字相加

array([ 6, 15, 24])

In [80]:
np.mean(a)

5.0

In [81]:
np.mean(a,axis=0)#列

array([4., 5., 6.])

In [82]:
np.mean(a,axis=1)#行

array([2., 5., 8.])

In [83]:
np.random.uniform(1,100)#产生1-100中的随机数

92.02973628233178

In [84]:
np.tile(a,(2,3))#行重复两次，列重复三次

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9, 7, 8, 9],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9, 7, 8, 9]])

In [86]:
np.argsort(a)#对行进行排序，按下标

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [87]:
a.argsort(axis=0)#对列排序

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [88]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [90]:
np.transpose(a)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [91]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
b=np.array([4,5,6])
for i in range(3):
    a[i,:]+=b

In [94]:
a

array([[ 9, 12, 15],
       [12, 15, 18],
       [15, 18, 21]])

In [95]:
a+np.tile(b,(3,1))

array([[13, 17, 21],
       [16, 20, 24],
       [19, 23, 27]])